terraform/pttp-shared-services-infrastructure.tf, terraform/staff-device-dhcp-server.tf, terraform/staff-device-dns-dhcp-admin.tf, terraform/staff-device-dns-dhcp-infrastructure.tf, terraform/staff-device-dns-server.tf, terraform/staff-device-docker-base-images.tf, terraform/staff-device-logging-dns-dhcp-integration-tests.tf, terraform/staff-device-logging-infrastructure.tf, terraform/staff-device-logging-syslog-to-cloudwatch.tf
Added DNS\DHCP and IMA team members to:
- pttp-shared-services-infrastructure
- staff-device-dhcp-server
- staff-device-dns-dhcp-admin
- staff-device-dns-dhcp-infrastructure
- staff-device-dns-server
- staff-device-docker-base-images
- staff-device-logging-dns-dhcp-integration-tests
- staff-device-logging-infrastructure
- staff-device-logging-syslog-to-cloudwatch
=> Add Made Tech collaborators to PTTP repositories 

lib/github_collaborators/terraform_collaborator.rb, spec/terraform_collaborator_spec.rb
Prior to this change, there was an implicit
requirement for any supplied values to have
nothing after the closing quote. So, this would be
fine:
```
foo = "bar"
```
...but this would count as missing the value of
`foo`:
```
foo = "bar" # some comment here
```
With this change, such comments will be ignored,
as they should be.
Although other text on the same line will also be
allowed, the combination of `terraform fmt` and
`terraform plan` which runs on every PR should 
prevent malformed code from getting through.
=> Allow comments in terraform source

.github/workflows/terraform-apply.yml
We update the report daily, to pick up any changes to collaborators that
have been made by users.
This change also posts an update to the report after we merge any
changes to this repository, so that the report is up to date wrt. those
changes, too.
=> After making changes, update the OpsEng report

.github/workflows/terraform-apply.yml
While I'm generating lots of PRs for individual changes, I don't want lots of `terraform apply` commands running in parallel, or to have to wait 5 minutes between each PR merge.
So, I'm temporarily disabling this bit of automation - I'll use the workflow-dispatch trigger to run the terraform apply for every few changes, rather than for each change.
=> Disable "apply on merge"

.github/workflows/targeted-terraform-plan.yml, .github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml, scripts/targeted-plan.sh, terraform/main.tf
- Remove `bucket` and `region` from `main.tf`
- Use DynamoDB table to lock terraform state
- Move the terraform state to a new path in S3
=> Terraform: state-locking & change location

.github/workflows/post-data.yaml, README.md, bin/remove-undefined-collaborators.rb, lib/github_collaborators.rb, lib/github_collaborators/access_remover.rb, lib/github_collaborators/http_client.rb, lib/github_collaborators/issue_creator.rb, lib/github_collaborators/terraform_collaborator.rb, spec/access_remover_spec.rb, spec/issue_creator_spec.rb, spec/terraform_collaborator_spec.rb
This PR adds code and github actions config. to remove access for any collaborators who are not defined in terraform code.
This means anyone who has been manually granted access to a repo, via the github UI, will have their access revoked overnight.
An issue is created, in the relevant repo, explaining how to get access which will not be removed.
- Add TerraformCollaborator#remove method
- Add code to remove collaborators
- Add ruby script to remove undefined collaborators
- Update script: take all config from ENV vars.
- Remove undefined collabs after report is updated
=> Remove undefined collaborators

terraform/bai2.tf, terraform/bankline-direct-parser.tf, terraform/modules/repository-collaborators/variables.tf, terraform/mojfile-uploader.tf, terraform/mt940-writer.tf, terraform/tax-tribunals-datacapture.tf, terraform/tax-tribunals-downloader.tf
Also, remove mentions of "triage" and "admin" permissions from the documentation and examples - they don't work, because of [this bug](https://github.com/integrations/terraform-provider-github/issues/480#issuecomment-636590471) in the GitHub API.
fixes #106 
fixes #97
=> Change "maintain" to "push" in collaborations

README.md
I meant to remove this in an earlier commit, but it turns out I hadn't saved the file after making this change.
=> Remove "maintain" & "triage" from permission opts.

terraform/yjaf-ui.tf
terraform fails if there are duplicated entries using the same value for
`github_user`, in the same repository.
i.e. you can't grant a user access to a repo multiple times.
=> Remove duplicate entries; chris-nps, mat-nps

.github/workflows/terraform-apply.yml
[Commit 09d996](https://github.com/ministryofjustice/github-collaborators/commit/2575d4b1705df2ca5a7274c768eedd546e09d996) replaced `OPS_ENG_REPORTS_URL` with `OPERATIONS_ENGINEERING_REPORTS_HOST` as the environment variable for `bin/post-data.sh`.
This PR adds the new environment variable to the terraform-apply.yml GitHub workflow, which [fails](https://github.com/ministryofjustice/github-collaborators/runs/1950157529) because the (correct) environment variable cannot be found.
=> Update env var for  to post data to the correct URL

terraform/curious-API.tf
Changing permission from write to push as write is not a valid variable accepted by the Github API.
=> Change permission from `write` to `push`

terraform/staff-infrastructure-monitoring-config.tf
We need to publish metrics for the new service and need to make pull
requests to this internal repository.
=> Allow NAC (Network Access Control) team to manage Grafana dashboard

terraform/transit-gateways.tf
This is to enable Delius support access to create transit gw attachments/resource access management.
=> Add repo transit-gateways and assign Stuart push access

terraform/modernisation-platform-environments.tf
Since techdata have completed their engagement with the Equip project, there is no need to continue to allow them repository access
=> remove techdata users

terraform/modernisation-platform-environments.tf
This is required for the 3rd party team Lumen to work on the PPUD modernisation platform accounts.
=> Give PPUD developers MP-env access

terraform/aws-root-account.tf
Hi there
The collaborator bjpirt was found to be missing from the file/s in this pull request.
=> Add full Org member / collaborator to Terraform file/s for bjpirt

terraform/yjaf-pnomis.tf
Hi there
The collaborator VasilDimitrov22 review date has expired for the file/s contained in this pull request.
=> Remove expired collaborator from Terraform file/s for VasilDimitrov22

terraform/bichard7-next-ui.tf
Hi there
The collaborator tomvaughan77 permission on Github is different to the permission in the Terraform file for the repository.
This is because the collaborator is a full organization member, is able to join repositories outside of Terraform and may have different access to the repository now they are in a Team.
The permission on Github is given the priority.
This pull request ensures we keep track of those collaborators, which repositories they are accessing and their permission.
Permission can either be admin, push, maintain, pull or triage.
=> Modify permission in Terraform file/s for tomvaughan77

terraform/hmpps-vcms-infra-versions.tf, terraform/hmpps-vcms-terraform.tf
Hi there
The collaborator miriamgo-civica was found to be missing from the file/s in this pull request.
=> Add full Org member / collaborator to Terraform file/s for miriamgo-civica

terraform/hmpps-vcms-app-cp.tf
Hi there
The collaborator simoncreasy-civica permission on Github is different to the permission in the Terraform file for the repository.
This is because the collaborator is a full organization member, is able to join repositories outside of Terraform and may have different access to the repository now they are in a Team.
The permission on Github is given the priority.
This pull request ensures we keep track of those collaborators, which repositories they are accessing and their permission.
Permission can either be admin, push, maintain, pull or triage.
=> Modify permission in Terraform file/s for simoncreasy-civica

terraform/hmpps-domestic-abuse-support-officers.tf
Hi there
The collaborator shaunthornburgh permission on Github is different to the permission in the Terraform file for the repository.
This is because the collaborator is a full organization member, is able to join repositories outside of Terraform and may have different access to the repository now they are in a Team.
The permission on Github is given the priority.
This pull request ensures we keep track of those collaborators, which repositories they are accessing and their permission.
Permission can either be admin, push, maintain, pull or triage.
=> Modify permission in Terraform file/s for shaunthornburgh

terraform/hmpps-domestic-abuse-support-officers.tf, terraform/hmpps-vcms-infra-versions.tf, terraform/hmpps-vcms.tf
Hi there
The collaborator simoncreasy-civica was found to be missing from the file/s in this pull request.
=> Add full Org member / collaborator to Terraform file/s for simoncreasy-civica

terraform/aws-root-account.tf
Hi there
The collaborator emileswarts permission on Github is different to the permission in the Terraform file for the repository.
This is because the collaborator is a full organization member, is able to join repositories outside of Terraform and may have different access to the repository now they are in a Team.
The permission on Github is given the priority.
This pull request ensures we keep track of those collaborators, which repositories they are accessing and their permission.
Permission can either be admin, push, maintain, pull or triage.
=> Modify permission in Terraform file/s for emileswarts

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator gregi2n has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for gregi2n

terraform/yjaf-ui.tf
Hi there
The collaborator angelanec has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for angelanec

terraform/hmpps-approved-premises-api.tf, terraform/hmpps-approved-premises-ui.tf, terraform/hmpps-temporary-accommodation-ui.tf
hmpps-approved-premises-api is the backend of 2 "community accommodation service" frontends:
- Approved Premises (CAS1) hmpps-approved-premises-ui
- Temporary Accommodation (CAS3) hmpps-temporary-accommodation-ui
These 3 apps are being pen. tested together by NCC.
=> Add pen. tester to 'accommodation service' repos

terraform/hmpps-approved-premises-api.tf, terraform/hmpps-approved-premises-ui.tf, terraform/hmpps-temporary-accommodation-ui.tf
hmpps-approved-premises-api is the backend of 2 "community accommodation service" frontends:
- Approved Premises (CAS1) hmpps-approved-premises-ui
- Temporary Accommodation (CAS3) hmpps-temporary-accommodation-ui
These 3 apps are being pen. tested together by NCC.
=> Add 3 further pen. testers from NCC to 'accommodation' repos

terraform/hmpps-integration-api-docs.tf
Hi there
The collaborator mcoffey-mt was found to be missing from the file/s in this pull request.
=> Add full Org member / collaborator to Terraform file/s for mcoffey-mt

terraform/hmpps-integration-api-docs.tf
Hi there
The collaborator chubberlisk was found to be missing from the file/s in this pull request.
=> Add full Org member / collaborator to Terraform file/s for chubberlisk

terraform/hmpps-integration-api-docs.tf
Hi there
The collaborator emileswarts was found to be missing from the file/s in this pull request.
=> Add full Org member / collaborator to Terraform file/s for emileswarts

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator howiedouglasaccessgroup has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for howiedouglasaccessgroup

terraform/hmpps-integration-api-docs.tf
Hi there
The collaborator aprilmd was found to be missing from the file/s in this pull request.
=> Add full Org member / collaborator to Terraform file/s for aprilmd

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator vcurtis-w14 has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for vcurtis-w14

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator abaldwin-caci has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for abaldwin-caci

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator ameldrum86 has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for ameldrum86

terraform/github-collaborators.tf
This PR adds a new collaborator to GitHub Collaborators repo. At present collaborators can't create branches to submit PRs for changes to their teams and remove or add users to their repos. This results in either a forked PR, which fails checks and means that either Operations Engineering has to replicate the PR, or manually create a PR from a submitted issue.
This will allow better self-service for this team and reduce manual intervention from Ops Eng.
- Added collaborator
=> Add collaborator to GitHub Collaborators

terraform/alpha_cjs_va_dashboard.tf
Hello 
We have a couple of outside collaborators working on the alpha cjs va dashboard project. Due to cloud deployment requirements, we are forced to change the name of the repo to alpha-cis-va-dashboard. I have now updated the tf file with the new repo name. 
If there are any more changes required anywhere else, please let me know. 
Thanks,
Vinoth Mohanram
=> Updated repo name in tf file

terraform/yjsm-ui.tf
PR to add Fabio Salvarezza as an outside collaborator [#2205](https://github.com/ministryofjustice/github-collaborators/issues/2205#issue-2501204211)
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the terraform/ directory.
Please supply all the requested information, so that your request can be processed as quickly as possible.
Which MoJ repository/s are you requesting access to (e.g. money-to-prisoners)?
yjsm-ui
What is the GitHub username of the person who needs access?
fabiosalvarezza
What is their full name?
Fabio Salvarezza
What is their email address?
[fabio.salvarezza@necsws.com](mailto:fabio.salvarezza@necsws.com)
What company/organisation do they belong to (e.g. "Department for Education")?
NEC
What level of access should …
=> Add outside collaborator

terraform/pfs-software-services_ansible.tf, terraform/pfs-software-services_terraform.tf
- This PR correct repository names in collaborator modules. This will fix access issues for collaborators.
- update module `pfs-software-services_terraform.tf`
- update module `pfs-software-services_ansible.tf`
- Issues linked
=> Correct repository names in collaborator modules

terraform/hmcts-courtfines.tf
Request to add the following as an external collaborator:
Matthew Harman
[#2246](https://github.com/ministryofjustice/github-collaborators/issues/2246)
github_user  = "mharman1973"
permission   = "admin"
name         = "Matthew Harman"
email        = "matthew.harman@hmcts.net"
org          = "CGI IT UK Ltd"
reason       = "Transition of project to CGI"
added_by     = "david.pearce@justice.gov.uk"
review_after = "2025-10-16"
=> Add mharman

terraform/hmpps-community-accommodation-tier-2-bail-prototypes.tf
Adds the last few people to the repository so that they can work on prototypes.
=> Add Zaizi team to the CAS 2 Bail repo

terraform/modernisation-platform-environments.tf
Tracked upstream by https://github.com/ministryofjustice/modernisation-platform/issues/8706
This PR adds external devops engineers who will work on the Youth Justice Board `youth-justice-app-framework` migration.
=> Added external collaborators for Modernisation Platform `youth-justice-app-framework`
