terraform/testing-external-collaborators.tf
Another change to test github actions
=> Replace toonsend w. DangerDawson

terraform/yjaf-ui.tf
This copies the changes from #17, but the checks for that PR are
failing, possibly because it's from a fork rather than a branch.
=> Add oliviergaubert to yjaf-ui

terraform/MOJ-PTTP-DevicesAndApps-Pipeline-Windows10Apps.tf, terraform/staff-device-management-ios-apps.tf, terraform/staff-device-management-ios-configuration.tf, terraform/staff-device-management-virtualdesktop.tf, terraform/staff-device-management-windows10-apps.tf, terraform/staff-device-management-windows10-configuration.tf, terraform/staff-infrastructure-azure-landing-zone.tf
Added relevant contact details for Sol-Tec engineers working on the PTTP programme
=> Staff infrastructure changes

bin/external-collaborators.rb
This was completely wrong - presumably a copy/
paste error on my part.
=> Correct the base URL for links to files

terraform/staff-infrastructure-metric-aggregation-server.tf, terraform/staff-infrastructure-monitoring-blackbox-exporter.tf, terraform/staff-infrastructure-monitoring-config.tf, terraform/staff-infrastructure-monitoring-snmpexporter.tf, terraform/staff-infrastructure-monitoring.tf
Same as #25, with the changes pulled from the fork to a branch.
Having the changes on a fork seems to cause problems for the code-formatter and terraform plan github actions
=> Add Made Tech Collaborators to PTTP IMA repos

terraform/apvs-ansible.tf, terraform/apvs-asynchronous-worker.tf, terraform/apvs-azurerm.tf, terraform/apvs-external-web.tf, terraform/apvs-internal-web.tf, terraform/apvs-packer.tf, terraform/apvs-puppet.tf, terraform/apvs.tf
Information supplied by Phoebe Crossland - PM on the APVS project.
Once this PR has been approved and merged, all other apvs-* repositories will be updated with similar details.
=> Update APVS collaborators

terraform/wmt-ansible.tf, terraform/wmt-azurerm.tf, terraform/wmt-data-migration.tf, terraform/wmt-etl.tf, terraform/wmt-jmeter.tf, terraform/wmt-packer.tf, terraform/wmt-probation-rules.tf, terraform/wmt-puppet.tf, terraform/wmt-web.tf, terraform/wmt-worker.tf
Project: Worker Management Tool (WMT)
PM: Shazad Mohammed
=> Update collaborators for active WMT repos

lib/github_collaborators/last_commit.rb, spec/fixtures/repositories.json, spec/fixtures/repository.json, spec/last_commit_spec.rb, spec/repositories_spec.rb, spec/repository_spec.rb
- Add more specs, Repository and Repositories
- Add a test to protect last_commit calls
=> Add more tests

terraform/staff-infrastructure-monitoring-config.tf
=> Add J Bevan to enable updating Grafana dashboards for DNS/DHCP

bin/import-repository-collaborators.rb
Fix syntax error and update outdated calls.
=> Fix broken 'bin/import-repository-collaborators.rb` script

.github/workflows/terraform-apply.yml
The initial purge of undocumented github collaborators is completed (barring one PR I'm going to use to trigger this action), so these workflow steps can be reinstated.
=> Reinstate apply & report on merge

terraform/bai2.tf, terraform/bankline-direct-parser.tf, terraform/mt940-writer.tf
[bai2](https://github.com/ministryofjustice/bai2), [bankline-direct-parser](https://github.com/ministryofjustice/bankline-direct-parser), [mt940-writer](https://github.com/ministryofjustice/mt940-writer)
Ian was formerly on the HMPPS Prisoner Money team and it would be good to grant maintenance privileges
=> Add ibrechin as a collaborator to open-source python libraries

terraform/staff-device-dns-dhcp-admin.tf
Adding this from fork PR elcorbs:patch-1
=> Add emma as a collaborator to dns/dhcp from elcorbs:patch-1 fork

terraform/staff-device-management-virtualdesktop.tf
Add jabenny to repo staff-device-management-virtualdesktop as per this [issue](https://github.com/ministryofjustice/staff-device-management-virtualdesktop/issues/2)
=> Update staff virtual desktop repo users

terraform/staff-device-management-virtualdesktop.tf
Correct "added_by" format and add Team email distribution
=> Update sol tech colab users

terraform/yjaf-app-template.tf, terraform/yjaf-assets.tf, terraform/yjaf-auth.tf, terraform/yjaf-bands.tf, terraform/yjaf-bed-unlock.tf, terraform/yjaf-case.tf, terraform/yjaf-cmm.tf, terraform/yjaf-conversions.tf, terraform/yjaf-csppi.tf, terraform/yjaf-dal.tf, terraform/yjaf-documents.tf, terraform/yjaf-gateway.tf, terraform/yjaf-mule-hub-connector.tf, terraform/yjaf-mule-mis-processor.tf, terraform/yjaf-nginx-gateway.tf, terraform/yjaf-nginx-pentaho.tf, terraform/yjaf-placements.tf, terraform/yjaf-refdata.tf, terraform/yjaf-returns.tf, terraform/yjaf-sentences.tf, terraform/yjaf-transfers.tf, terraform/yjaf-utilities.tf, terraform/yjaf-views.tf, terraform/yjaf-workflow.tf, terraform/yjaf-yp.tf
=> Add user JWGNPS to all yjaf-* repos

terraform/staff-device-dhcp-server.tf, terraform/staff-device-dns-dhcp-admin.tf, terraform/staff-device-dns-dhcp-infrastructure.tf, terraform/staff-device-dns-server.tf, terraform/staff-device-docker-base-images.tf, terraform/staff-device-logging-dns-dhcp-integration-tests.tf, terraform/staff-device-logging-infrastructure.tf, terraform/staff-device-logging-syslog-to-cloudwatch.tf, terraform/staff-device-shared-services-infrastructure.tf
Jiv and Caitlin have completed their work and moved on.
Deleted from PTTP repos.
=> Removed Made Tech

terraform/bai2.tf, terraform/bankline-direct-parser.tf, terraform/mojfile-uploader.tf, terraform/mt940-writer.tf, terraform/tax-tribunals-datacapture.tf, terraform/tax-tribunals-downloader.tf
This replaces the collaborations which were removed by #114 and #115
=> Reinstate collaborations

terraform/staff-device-management-admin.tf
Add new external collaborator tf file for new github repo
=> New tf for new repo

terraform/bichard7-next-infrastructure.tf, terraform/bichard7-next-pnc-emulator.tf, terraform/bichard7-next-services.tf, terraform/bichard7-next.tf, terraform/moj-cjse-bichard7.tf
- Add a new repo
- Remove a user from the existing repos
=> Update bichard7 repositories

terraform/hmpps-pin-phone-monitor-api.tf, terraform/hmpps-pin-phone-monitor.tf
Read isn't a valid permission so switching to use pull
https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_collaborator
=> Switch to use pull instead of read permission.

terraform/staff-infrastructure-monitoring-deployments.tf
add collaborators to staff-infrastructure-monitoring-deployments.
=> Add Collaborators

terraform/tax-tribunals-datacapture.tf
=> Add QA Jemimah Kemirembe

terraform/hmpps-cporacle-application.tf
=> Add collaborators for HMPPS CP Oracle application

terraform/hmpps-vcms.tf
=> Add collaborators for HMPPS VCMS repository

terraform/staff-device-shared-services-infrastructure.tf
This is for the Network Access Control team to spin up build pipelines
=> Add collaborators for PTTP Shared Services

terraform/hmpps-cporacle-application.tf
Remove aliuk2012 who no longer works on this project
=> Remove collaborator

terraform/curious-API.tf
This PR removes graadi and adds bharaatt
=> Add and remove collaborator

terraform/mlap-sandpit.tf
Adding Mobilise collaborators to MLAP sandpit repo
=> Create mlap-sandpit repository

terraform/staff-device-management-windows10-apps.tf
Adding new collaborators. Replaces https://github.com/ministryofjustice/github-collaborators/pull/217/files which is a fork, rather than branch of main.
=> Add new collaborators

terraform/curious-API.tf
bharaatt permissions changed to allow user to make changes
=> Amend bharaatt permissions

terraform/wmt-ansible.tf, terraform/wmt-azurerm.tf, terraform/wmt-data-migration.tf, terraform/wmt-etl.tf, terraform/wmt-jmeter.tf, terraform/wmt-packer.tf, terraform/wmt-probation-rules.tf, terraform/wmt-puppet.tf, terraform/wmt-web.tf, terraform/wmt-worker.tf
Updates to `review_after` dates for multiple wmt repositories as agreed with owner.
=> Update collaborator `review_after` dates

terraform/yjaf-conversions.tf
Removed as invite is stale. Not accessed repo.
=> Remove collaborator djv72

.github/workflows/repository-check.yaml, scripts/repository-check.sh
Added in a basic repository check to see what repositories have been taken down
=> Added in repository check workflow

terraform/staff-infrastructure-azure-landing-zone.tf
Sol-tec are no longer involved in the project thus removing their access
=> Removing Soltec resources from ALZ repo

terraform/network-access-control-admin.tf
This is required to build new features
=> Add myself as a collaborator

terraform/bichard7-next-audit-logging.tf, terraform/bichard7-next-beanconnect.tf, terraform/bichard7-next-infrastructure-docker-images.tf, terraform/bichard7-next-infrastructure.tf, terraform/bichard7-next-pnc-emulator.tf, terraform/bichard7-next-tests.tf, terraform/bichard7-next-user-service.tf, terraform/bichard7-next.tf, terraform/moj-cjse-bichard7.tf
Addresses https://github.com/ministryofjustice/github-collaborators/issues/250
=> Reinstate Bichard users

terraform/network-access-control-infrastructure.tf, terraform/network-access-control-integration-tests.tf, terraform/network-access-control-server.tf
Lost access somehow, adding myself here.
=> Add myself to all the Network Access Control Service repos

terraform/bichard7-next-tests.tf
Collaborator permission type updated to fix pipeline
=> Update praveenmadan permission

terraform/delius.tf, terraform/recalldecision-prototype.tf
Add Rebecca Cryan and move Ryan haney to recalldecision-prototype repo
=> tidy making recall decision access

terraform/pfs-software-services_code.tf
New Collaborator request for external supplier Kainos
=> New Collaborator

terraform/staff-device-dhcp-server.tf, terraform/staff-device-dns-dhcp-admin.tf, terraform/staff-device-dns-dhcp-infrastructure.tf, terraform/staff-device-dns-server.tf, terraform/staff-device-docker-base-images.tf, terraform/staff-device-logging-dns-dhcp-integration-tests.tf, terraform/staff-device-logging-infrastructure.tf, terraform/staff-device-logging-syslog-to-cloudwatch.tf, terraform/staff-device-shared-services-infrastructure.tf, terraform/staff-infrastructure-monitoring-blackbox-exporter.tf, terraform/staff-infrastructure-monitoring-config.tf, terraform/staff-infrastructure-monitoring-deployments.tf, terraform/staff-infrastructure-monitoring.tf, terraform/staff-infrastructure-network-services.tf
Adding Neil Kidd from Made Tech to Cloud Ops Repo's for assisting on PTTP project work.
=> add-neil-kidd-to-cloudops-repos

terraform/bai2.tf
Review date updated in agreement with repo owner
=> Update review date

terraform/staff-device-management-windows10-apps.tf
Add new Content and Cloud engineer with access
=> Matthew white mo j patch 1

.github/workflows/approved-email-check.yml, scripts/approved-email-domain-check.py
changes to update the team before each operation on the team or repo and remove the venv from yml file
=> fix the team data being out of date during a run

terraform/yjaf-auth.tf
Update to admin for dependabot alerts
=> Change collaborator permissions

terraform/bichard7-next-audit-logging.tf, terraform/bichard7-next-beanconnect.tf, terraform/bichard7-next-core.tf, terraform/bichard7-next-data.tf, terraform/bichard7-next-help.tf, terraform/bichard7-next-infrastructure-docker-images.tf, terraform/bichard7-next-infrastructure-modules.tf, terraform/bichard7-next-infrastructure.tf, terraform/bichard7-next-pnc-emulator.tf, terraform/bichard7-next-reporting.tf, terraform/bichard7-next-shared-infrastructure.tf, terraform/bichard7-next-tests.tf, terraform/bichard7-next-user-service.tf, terraform/bichard7-next.tf, terraform/moj-cjse-bichard7.tf
Sets Jamie Davies as admin so we have > 1 admin
=> Update access to Bichard repos

terraform/staff-device-management-windows10-mass-storage-controls.tf
=> fix typo in repo name

terraform/hmpps-delius-api.tf
Also reduces existing access from "admin" to "push"
=> Grant access for Sean Valmonte to hmpps-delius-api

terraform/modernisation-platform-environments.tf
TechData are building the infrastructure for HMPPS Equip application in
the Modernisation Platform, this gives the 2 engineers access to the
repository they need.
=> Give TechData access to modernisation platform rep

terraform/modernisation-platform-environments.tf
John is the tech lead for Roc Technolgies who are building and
supporting the Equip application in the modernisation platform.
=> Add John Broom as a collaborator

terraform/staff-device-management-intune-scripts-prod.tf, terraform/staff-device-management-virtualdesktop.tf, terraform/staff-device-management-windows10-apps.tf
Add new TF file for new repo and cleanup leavers from other MoJ OFFICIAL Repos
=> add new TF for new repo and remove obsolete collaborators from others

terraform/hmpps-vcms.tf
Code owner has confirmed that collaborator review_after date can be extended.
=> Collaborator review_after extended

terraform/bai2.tf, terraform/bankline-direct-parser.tf, terraform/mt940-writer.tf
C.f.
• [bankline-direct-parser#7](https://github.com/ministryofjustice/bankline-direct-parser/issues/7)
• [mt940-writer#8](https://github.com/ministryofjustice/mt940-writer/issues/8)
=> Renew @ibrechin as collaborator for python libs

terraform/hmpps-vcms-infra-versions.tf
Based on our team ticket https://dsdmoj.atlassian.net/browse/NIT-147
Adding Civica engineers to be able to write to hmpps-vcms-infra-versions.
=> Adding Civica engineers to be able to write to hmpps-vcms-infra-versions

terraform/yjaf-serious-incidents.tf
Create yjaf-serious-incidents repository and add collaborators
=> Create yjaf-serious-incidents repository

terraform/sharepoint-intranet-support.tf
Working on the Sharepoint intranet, we need to put some workflows and other custom code used in MS365 under source control.
=> Added Domenykas as a collaborator

terraform/modernisation-platform-environments.tf
=> Revert add parrokajadm

terraform/modernisation-platform-environments.tf
Collaborator keeps getting removed as ID is incorrect.
=> Correct collaborator GitHub ID

terraform/staff-device-management-intune-scripts.tf, terraform/staff-device-management-ios-apps.tf, terraform/staff-device-management-ios-configuration.tf, terraform/staff-device-management-virtualdesktop.tf, terraform/staff-device-management-windows10-apps.tf, terraform/staff-device-management-windows10-mass-storage-controls.tf, terraform/staff-infrastructure-azure-landing-zone-spoke-eucs.tf
Add new Developers from MadeTech with same access as C+C lead dev. Amend dates of C+C resources to align to contract end
=> Add new MT devs and amend C+C review date

terraform/staff-device-management-virtualdesktop.tf
amend the staff-device-management-virtualdesktop repo to give additional C+C collaborator access
=> amend C+C access to repo

terraform/yjaf-assets.tf, terraform/yjaf-serious-incidents.tf
Removed due to expired invites
=> Remove collaborators

terraform/hmpps-domestic-abuse-support-officers.tf, terraform/hmpps-vcms-infra-versions.tf, terraform/hmpps-vcms.tf
Hi there
The collaborator simoncreasy-civica review date has expired for the file/s contained in this pull request.
=> Remove expired collaborator from Terraform file/s for simoncreasy-civica

terraform/yjaf-datateam.tf, terraform/yjaf-transitions.tf
Hi there
The collaborator craig-ashford review date has expired for the file/s contained in this pull request.
=> Remove expired collaborator from Terraform file/s for craig-ashford

terraform/sharepoint-intranet-support.tf
Hi there
The collaborator dkardokas review date has expired for the file/s contained in this pull request.
=> Remove expired collaborator from Terraform file/s for dkardokas

terraform/hmpps-domestic-abuse-support-officers.tf, terraform/hmpps-vcms.tf
Hi there
The collaborator ahmedwaqaralam review date has expired for the file/s contained in this pull request.
=> Remove expired collaborator from Terraform file/s for ahmedwaqaralam

terraform/sharepoint-intranet-support.tf
Hi there
The Terraform files in this pull request are empty and serve no purpose, please remove them.
=> Delete empty Terraform file/s

terraform/hmpps-integration-api.tf
- Add April as a team member to [HMPPS Integration API repository](https://github.com/ministryofjustice/hmpps-integration-api).
=> Add team member to HMPPS Integration API repository

terraform/hmpps-vcms-app-cp.tf
Hi there
The collaborator miriamgo-civica has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for miriamgo-civica

terraform/hmpps-vcms-app-cp.tf
Hi there
The collaborator simoncreasy-civica has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for simoncreasy-civica

terraform/moj-pttp-devicesandapps-pipeline-windows10apps.tf, terraform/staff-device-management-intune-scripts.tf, terraform/staff-device-management-ios-apps.tf, terraform/staff-device-management-ios-configuration.tf, terraform/staff-device-management-virtualdesktop.tf, terraform/staff-device-management-windows10-apps.tf, terraform/staff-device-management-windows10-mass-storage-controls.tf, terraform/staff-infrastructure-azure-landing-zone-spoke-eucs.tf
Amend access for MadeTech and Content+Cloud users
=> Update mojo repos

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator tmamedova has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for tmamedova

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator suraj-necsws has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for suraj-necsws

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator robgibsoncapita has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for robgibsoncapita

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator richardwheatleycapita has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for richardwheatleycapita

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator paulfitzgerald-advanced has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for paulfitzgerald-advanced

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator kieran-tanner has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for kieran-tanner

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator griffinjuknps has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for griffinjuknps

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator bryanmaguireadvanced has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for bryanmaguireadvanced

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator balpurewal has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for balpurewal

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator vkolesnikovas has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for vkolesnikovas

terraform/yjsm-hub-svc.tf, terraform/yjsm-hub.tf, terraform/yjsm-hubadmin.tf
Hi there
The collaborator vikasnecsws has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for vikasnecsws

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator yarseyah has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for yarseyah

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator schungcaci has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for schungcaci

terraform/aws-root-account.tf
Hi there
The collaborator bjpirt has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for bjpirt

terraform/yjaf-gateway-proxy.tf
Hi there
The collaborator stephenhobden has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for stephenhobden

terraform/yjaf-app-template.tf, terraform/yjaf-devops-infrastructure.tf, terraform/yjaf-gateway-proxy.tf, terraform/yjaf-gateway.tf, terraform/yjaf-infra-aws-mgmt.tf, terraform/yjaf-mule-hub-connector.tf, terraform/yjaf-mule-mis-processor.tf, terraform/yjaf-nginx-gateway.tf, terraform/yjaf-nginx-pentaho.tf, terraform/yjaf-poc-app.tf, terraform/yjaf-poc.tf, terraform/yjaf-ui.tf
Hi there
The collaborator ttipler has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for ttipler

terraform/offender-events-ui.tf
Hi there
Please merge this pull request to add the outside collaborator to the Terraform files / GitHub.
If you have any questions, please post in #ask-operations-engineering on Slack.
=> Add collaborator to Terraform file/s from Issue for multiple-collaborators

terraform/pfs-software-services_rdp.tf, terraform/pfs-software-services_terraform.tf
Hi there
The collaborator nathanials has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for nathanials

terraform/pfs-software-services_rdp.tf, terraform/pfs-software-services_terraform.tf
Hi there
The collaborator simongivan has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for simongivan

terraform/yjaf-cmm.tf, terraform/yjsm-hub-svc.tf, terraform/yjsm-hub.tf, terraform/yjsm-hubadmin.tf
Hi there
Please merge this pull request to add the outside collaborator to the Terraform files / GitHub.
If you have any questions, please post in #ask-operations-engineering on Slack.
=> Add collaborator to Terraform file/s from Issue for angelanec

terraform/ndelius-serenity-automation.tf
Adding Michal Laskowski as collaborator to ndelius-serenity-automation. Note I needed to create a new file for the ndelius-serenity-automation repository.
=> mlaskowski4 => ndelius-serenity-automation

terraform/hmpps-integration-api-docs.tf
To be reviewed in 6 months from today
=> Bump HMPPS Integration API review_after date

terraform/staff-device-management-intune-scripts.tf, terraform/staff-device-management-ios-apps.tf, terraform/staff-device-management-ios-configuration.tf, terraform/staff-device-management-windows10-apps.tf, terraform/staff-device-management-windows10-mass-storage-controls.tf, terraform/staff-infrastructure-azure-landing-zone-spoke-eucs.tf
Hi there
The collaborator bingliumt review date has expired for the file/s contained in this pull request.
=> Remove expired collaborator from Terraform file/s for bingliumt

terraform/staff-device-shared-services-infrastructure.tf
Hi there
The collaborator c-gyorfi has review date/s that are close to expiring.
=> Extend review date in Terraform file/s for c-gyorfi

terraform/staff-device-management-intune-scripts.tf, terraform/staff-device-management-ios-apps.tf, terraform/staff-device-management-ios-configuration.tf, terraform/staff-device-management-windows10-apps.tf, terraform/staff-device-management-windows10-mass-storage-controls.tf, terraform/staff-device-shared-services-infrastructure.tf, terraform/staff-infrastructure-azure-landing-zone-spoke-eucs.tf
Hi there
The collaborator jazjax review date has expired for the file/s contained in this pull request.
=> Remove expired collaborator from Terraform file/s for jazjax

terraform/bai2.tf, terraform/bankline-direct-parser.tf, terraform/mt940-writer.tf
Addresses:
https://github.com/ministryofjustice/bai2/issues/41
https://github.com/ministryofjustice/bankline-direct-parser/issues/10
https://github.com/ministryofjustice/mt940-writer/issues/10
=> Renew access for ibrechin

terraform/ndelius-test-automation.tf
to test-automation.  We did have an outstanding request to extend but that seems to have got lost.
=> Adding Andrew Richardson

terraform/hmpps-delius-api.tf
Extending review date for Michal and Peter
=> Extending review date

terraform/ndelius-test-automation.tf
Extending the date on Madan, Sean and Andrew so they can continue working on NDelius Test Automation.
Removing Alex.
=> Updates to Unilink Test Automation

terraform/yjaf-terraform.tf
- PR adds 3 collaborators to new yjaf-terraform repo
- Adds new module containing 3 collaborators to yjaf-terrafom repo
=> Add new collaborators to yjaf-terraform repository

terraform/yjaf-assets.tf, terraform/yjaf-auth.tf, terraform/yjaf-bands.tf, terraform/yjaf-bed-unlock.tf, terraform/yjaf-case.tf, terraform/yjaf-conversions.tf, terraform/yjaf-dal.tf, terraform/yjaf-datateam.tf, terraform/yjaf-documents.tf, terraform/yjaf-gateway-proxy.tf, terraform/yjaf-gateway.tf, terraform/yjaf-mule-hub-connector.tf, terraform/yjaf-placements.tf, terraform/yjaf-refdata.tf, terraform/yjaf-returns.tf, terraform/yjaf-sentences.tf, terraform/yjaf-serious-incidents.tf, terraform/yjaf-transfers.tf, terraform/yjaf-transitions.tf, terraform/yjaf-ui.tf, terraform/yjaf-utilities.tf, terraform/yjaf-views.tf, terraform/yjaf-workflow.tf, terraform/yjaf-yp.tf, terraform/yjsm-hub-svc.tf, terraform/yjsm-hub.tf, terraform/yjsm-hubadmin.tf, terraform/yjsm-ui.tf
- PR to extend collaborator `review_after` date on multiple repositories. Also updating business approver contact email.
- `review date` updated
- `added_by` updated
=> Extend collaborator review date

terraform/yjaf-gateway-proxy.tf
- PR to add new collaborator and update MoJ approver for all collaborators
- Added new collaborator
- Update `added_by` value for all collaborators on this repository
=> Add new collaborator and update MoJ approver details

terraform/yjsm-hubadmin.tf
- PR to change permission for a collaborator on a repository. Also updating MoJ contact details for all collaborators on the repository.
- Change permission for AndrewTRichards from `admin` to `push`
- Update `added_by` value for all collaborators in module
=> Change collaborator permission

terraform/yjaf-gateway-proxy.tf
=> Add new collaborator

terraform/yjaf-assets.tf, terraform/yjaf-auth.tf, terraform/yjaf-bands.tf, terraform/yjaf-bed-unlock.tf, terraform/yjaf-case.tf, terraform/yjaf-cmm.tf, terraform/yjaf-conversions.tf, terraform/yjaf-dal.tf, terraform/yjaf-datateam.tf, terraform/yjaf-documents.tf, terraform/yjaf-gateway-proxy.tf, terraform/yjaf-gateway.tf, terraform/yjaf-mule-hub-connector.tf, terraform/yjaf-mule-mis-processor.tf, terraform/yjaf-placements.tf, terraform/yjaf-refdata.tf, terraform/yjaf-returns.tf, terraform/yjaf-sentences.tf, terraform/yjaf-serious-incidents.tf, terraform/yjaf-transfers.tf, terraform/yjaf-transitions.tf, terraform/yjaf-ui.tf, terraform/yjaf-utilities.tf, terraform/yjaf-views.tf, terraform/yjaf-workflow.tf, terraform/yjaf-yp.tf, terraform/yjsm-hub-svc.tf, terraform/yjsm-hub.tf, terraform/yjsm-hubadmin.tf, terraform/yjsm-ui.tf
- PR to add collaborator to repositories. Also updates a number of `added_by` values to reflect changes in Service Owner.
- Add collaborator to 29 repos
- Extend `review_after` on 1 repo
- Updates `added_by` values in all yjaf related modules
=> Add collaborator

terraform/yjaf-assets.tf, terraform/yjaf-auth.tf, terraform/yjaf-bands.tf, terraform/yjaf-bed-unlock.tf, terraform/yjaf-case.tf, terraform/yjaf-cmm.tf, terraform/yjaf-conversions.tf, terraform/yjaf-dal.tf, terraform/yjaf-datateam.tf, terraform/yjaf-documents.tf, terraform/yjaf-gateway-proxy.tf, terraform/yjaf-gateway.tf, terraform/yjaf-mule-hub-connector.tf, terraform/yjaf-placements.tf, terraform/yjaf-refdata.tf, terraform/yjaf-returns.tf, terraform/yjaf-sentences.tf, terraform/yjaf-serious-incidents.tf, terraform/yjaf-transfers.tf, terraform/yjaf-transitions.tf, terraform/yjaf-ui.tf, terraform/yjaf-views.tf, terraform/yjaf-workflow.tf, terraform/yjaf-yp.tf, terraform/yjsm-hub-svc.tf, terraform/yjsm-hub.tf, terraform/yjsm-hubadmin.tf, terraform/yjsm-ui.tf
- PR adds collaborator `AndrewTRichards` to `yjsm-ui` repository and extends `review_after` date on all other repos
- Add `AndrewTRichards` to `yjsm-ui`
- Update `review_after` value on 27 repositories
=> Add collaborator and extend review_after dates

terraform/modernisation-platform-environments.tf
=> Remove expired collaborators

terraform/yjaf-terraform.tf
Gregory Whiting will be given access to yjaf-terraform repo
[Issue #2083](https://github.com/ministryofjustice/github-collaborators/issues/2083)
=> Add an external collaborator

terraform/legislation-drafting-helper.tf, terraform/yjaf-terraform.tf
Add a new external collaborator [#2086](https://github.com/ministryofjustice/github-collaborators/issues/2086):
Which MoJ repository/s are you requesting access to (e.g. money-to-prisoners)?
https://github.com/ministryofjustice/legislation-drafting-helper
What is the GitHub username of the person who needs access?
lmwilkigov
What is their full name?
Liam Wilkinson
What is their email address?
[liam.wilkinson@cabinetoffice.gov.uk](mailto:liam.wilkinson@cabinetoffice.gov.uk)
What company/organisation do they belong to (e.g. "Department for Education")?
Cabinet Office / No10
What level of access should they have?
Write
Why is this access being requested?
We are collaborating with no10 on a x-govt project relating to legislation.
Which MoJ team/person is responsible for this request? This …
=> Add liam wilkinson

terraform/delius-manual-deployments.tf, terraform/hmpps-delius-core-terraform.tf, terraform/hmpps-delius-pipelines.tf, terraform/hmpps-env-configs.tf, terraform/hmpps-ndelius-rbac.tf, terraform/hmpps-probation-integration-services.tf, terraform/ndelius-test-automation.tf, terraform/ndelius-um.tf
* Also extended access for existing Unilink collaborators.
=> Grant Michal Laskowski access to push to the hmpps-probation-integration-services repo

.github/workflows/check-collaborators-username.yml, .github/workflows/check-fork-status.yml, .github/workflows/close-expired-issues.yml, .github/workflows/create-pr-from-issue.yml, .github/workflows/delete-expired-invites.yml, .github/workflows/outside-collaborators-check.yaml, .github/workflows/repository-check.yaml, .github/workflows/targeted-terraform-plan.yml, .github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml, lib/github_collaborators/github_graph_ql_client.rb, lib/github_collaborators/http_client.rb, spec/github_graph_ql_client_spec.rb, spec/http_client_spec.rb
- Reducing the number of classic token in use and to adhere to POLP.
- ✨ A new Fine-grained PAT added to the repo secrets; `MOJ_COLLABORATORS_GENERAL_ADMIN_BOT_PAT`
- ♻️ Replaced instances of `OPS_BOT_TOKEN` with `MOJ_COLLABORATORS_GENERAL_ADMIN_BOT_PAT`
-
=> Switch over to Fine-grained PAT

terraform/alpha-cjs-va-dashboard.tf
Updated module name for alpha-cjs-va-dashboard
=> Updated module name

terraform/staff-device-management-virtualdesktop.tf
This PR adds an outside collaborator.  Request has been amended from 3 persons to 1 (change not reflected in the original issue #2194 - Nikolay Milyaev is now the only person to be added:
Use this issue template if you do not feel comfortable raising a PR with the required changes to files in the terraform/ directory.
Please supply all the requested information, so that your request can be processed as quickly as possible.
Which MoJ repository/s are you requesting access to (e.g. money-to-prisoners)?
[staff-device-management-virtualdesktop](https://github.com/ministryofjustice/staff-device-management-virtualdesktop)
What is the GitHub username of the person who needs access?
What is their full name?
Catrina Feely
Renu Sandy
Nikolay Milyaev
What is their email address? …
=> Add outside collaborator

terraform/ndelius-test-automation.tf
Neale Davison old account is locked and he can't reset it.  So has created a new account.  ND406
=> Change user ID

terraform/bichard7-next-audit-logging.tf, terraform/bichard7-next-beanconnect.tf, terraform/bichard7-next-core.tf, terraform/bichard7-next-data.tf, terraform/bichard7-next-help.tf, terraform/bichard7-next-infrastructure-docker-images.tf, terraform/bichard7-next-infrastructure.tf, terraform/bichard7-next-pnc-emulator.tf, terraform/bichard7-next-reporting.tf, terraform/bichard7-next-shared-infrastructure.tf, terraform/bichard7-next-user-service.tf, terraform/bichard7-next.tf
Bushra has left the Bichard team as of today. This PR removes her access to the Bichard repositories.
=> Remove access to Bichard repos for Bushra
